### ISSUE TITLE
The plugin throws "Properties must not be empty" when using data property as input

### ISSUE THREAD

**Issue by johardi** [protegeproject/existentialquery#2]
Steps to reproduce the error:
1. Open an ontology,
2. Open ExistentialQuery tab,
3. Run a reasoner.
4. Put any class entity in the "Subclass class expression"
5. Put any data property entity in the "Property expression" and execute

```
Uncaught Exception in thread 'AWT-EventQueue-0' 
java.lang.IllegalArgumentException: properties must not be empty
    at uk.ac.manchester.cs.owl.existentialquery.OWLExistentialReasonerImpl.computeExistentialFillers(OWLExistentialReasonerImpl.java:95) ~[na:na]
    at uk.ac.manchester.cs.owl.existentialquery.OWLExistentialReasonerImpl.getFillers(OWLExistentialReasonerImpl.java:72) ~[na:na]
    at uk.ac.manchester.cs.owl.existentialquery.ExistentialQueryViewComponent.doQuery(ExistentialQueryViewComponent.java:134) ~[na:na]
    at uk.ac.manchester.cs.owl.existentialquery.ExistentialQueryViewComponent.access$000(ExistentialQueryViewComponent.java:31) ~[na:na]
    at uk.ac.manchester.cs.owl.existentialquery.ExistentialQueryViewComponent$1.actionPerformed(ExistentialQueryViewComponent.java:62) ~[na:na]
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_40]
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346) ~[na:1.8.0_40]
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_40]
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_40]
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[na:1.8.0_40]
    at java.awt.Component.processMouseEvent(Component.java:6525) ~[na:1.8.0_40]
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_40]
    at java.awt.Component.processEvent(Component.java:6290) ~[na:1.8.0_40]
    at java.awt.Container.processEvent(Container.java:2234) ~[na:1.8.0_40]
...
```

**Comment by matthewhorridge** [comment]
Data properties aren't supported.  The parser should reject them.
